reporter: Use empty list as CC and BCC defaults
Use empty lists for CC and BCC address lists when they're unspecified,
instead of throwing an exception like this one:

Traceback (most recent call last):
  File "./bin/skt", line 11, in <module>
    sys.exit(main())
  File "./lib/python2.7/site-packages/skt/executable.py", line 1098, in main
    args.func(cfg)
  File "./lib/python2.7/site-packages/skt/executable.py", line 489, in cmd_report
    reporter = reporter_class(cfg)
  File "./lib/python2.7/site-packages/skt/reporter.py", line 508, in __init__
    self.mailcc = [cc.strip() for cc in cfg['reporter']['mail_cc']]
TypeError: 'NoneType' object is not iterable